version: "3.8"
services:
  crud:
    build: .
    environment:
      DB_HOST: "localhost"
      DB_PORT: "5432"
      DB_NAME: "db_crud"
      DB_USER: "usr_crud"
      DB_PASS: "Passw0rd"
    ports:
      - "8080:8080"
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: Passw0rd
    volumes:
      - local_pgdata:/var/lib/postgresql/data
      - ./init-db/:/docker-entrypoint-initdb.d/
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: khabirov.ar@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Passw0rd
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data: