version: "3.8"
services:
  crud:
    build: .
    environment:
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_NAME: "db_crud"
      DB_USER: "usr_crud"
      DB_PASS: "Passw0rd"
    ports:
      - "8080:8080"
    networks:
      - network
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: Passw0rd
    volumes:
      - local_pgdata:/var/lib/postgresql/data
      - ./init-db/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d mydatabase -U myuser"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - network
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: khabirov.ar@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Passw0rd
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - network

volumes:
  local_pgdata:
  pgadmin-data:

networks:
  network: